spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 
    url: jdbc:mysql://116.62.240.193:3306/sell?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql:true
logging:
  pattern:
    console: "%d - %msg%n"
  path: d:/
server: 
  max-http-header-size: 10240000
  tomcat: 
    max-http-header-size: 10240000
    max-http-post-size: 10240000
wechat:
  mpAppId: wxdef38d7055ecb07a
  mpAppSecret: 6c8115af3f12f100d3f9e0f45808e153
  mchId: 1518646571
  mchKey: tV7K1SqjzXmxa9qaLNIOo7RHxfAz3Lvg
  keyPath: i:/apiclient_cert.p12
  notifyUrl: http://nicedevelop.nat300.top/pay/notify