spring:
	datasource:
		driver-class-name: com.mysql.jdbc.driver
		user: bff459feb0b197
		password: 9babfc40
		url: us-cdbr-iron-east-02.cleardb.net/heroku_7f8b04b60249ef5?reconnect=true
	jpa:
		show-sql: true
